# Generated by Django 5.1.5 on 2025-01-21 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('barcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('accountType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.accounttype')),
            ],
        ),
        migrations.CreateModel(
            name='ShopingList',
            fields=[
                ('itemType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apis.itemtype')),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expirationDate', models.DateField()),
                ('amount', models.IntegerField()),
                ('itemType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.itemtype')),
            ],
        ),
    ]
